#!/bin/bash

#PBS -l walltime=10:00:00,nodes=1:ppn=10
#PBS -joe .
#PBS -d .
#PBS -l vmem=40g,mem=40g

if [ -z "$transcriptFile" ];
then
		echo "ERROR - Specify a path to a transcriptFile with the format:"
		echo "Gene	Type	Chrom	Start	End	NTimesSeen	NSamplesSeen	Samples:NSeen"
		echo "AL627309.1	BLAH	1	136903	136953	1	1	G34487:1"
		exit 1
fi

if [ -z "transcript_model" ];
then
	echo "Include a path to a transcript_model for junction annotation"
	exit 1
fi

home=~/tools/MendelianRNA-seq
name=`basename $transcriptFile`
sjdOutput="All."$name".splicing.list"

if [ -z "$processes" ];
then
		processes=10
fi

if [ -z "$bamList" ];
then
		bamList='bamlist.list'
fi

normOutput="norm-"$sjdOutput

module load python/3.5.2
python ~/tools/MendelianRNA-seq/Analysis/SpliceJunctionDiscovery.py -transcriptFile=$transcriptFile -bamList=$bamList -processes=$processes

module load python/2.7.11
$home/Analysis/NormalizeSpliceJunctionValues.py -transcript_model=$transcript_model -splice_file=$sjdOutput --normalize > $normOutput

rm $sjdOutput

# cat $normOutput | grep $sample | awk "{ if (\$5 == 1 && \$4 >= $minread ) print \$0 }" | sed "s/:$sample//" | sed "s/:$sample//" | awk "{if (\$7 == \"Neither\" || \$9 > $threshold) print \$0}" > $filteredOutput
